### ISSUE TITLE
OS: Log collection options

### ISSUE THREAD

**Issue by MihaiNueleanu** [kihosk/kiosk-os#2]
Briefly looked at log collection with papertrail standalone. And to my surprise, it was very easy to get it done.

On the raspberry, the following file was added:

/etc/rsyslog.d/70-ansible.conf
```
$ModLoad imfile
$InputFileName /home/pi/ansible.log
$InputFileTag ansible-log
$InputFileStateFile stat-ansible-log
$InputFileSeverity 0 1 2 3 4 5 6 7
$InputFileFacility local3
$InputRunFileMonitor

local3.*          @logs4.papertrailapp.com:42686
```

And, on papertrail's side:
https://papertrailapp.com/systems/setup?type=system&platform=unix#unix-manual
![image.png](https://images.zenhubusercontent.com/5f241f53c7cdabe34a5ab9e5/7bc0fc60-9f97-451c-bda8-3f59ce7757a9)

Result being:
![image.png](https://images.zenhubusercontent.com/5f241f53c7cdabe34a5ab9e5/d9167f82-a6d9-4de4-9b75-33ffd8fb102e)

Loosely inspired from:
https://medium.com/@vbmade2000/a-dead-simple-tutorial-on-how-to-forward-rsyslog-logs-to-a-file-130364c049fb

**Comment by MihaiNueleanu** [comment]
@joshuakarjala , fyi

**Comment by joshuakarjala** [comment]
> @joshuakarjala , fyi

Nice! looks good - question is of course .. what logs to send? How much will it be / cost wise

**Comment by MihaiNueleanu** [comment]
Of course.. 

Looks like papertrail has the same pricing as when used via heroku, more or less:
https://www.papertrail.com/plans/

What I'm basically looking for with this is - errors. Because for example we currently have no way of debugging this ansible bug, and something like this would give us a better chance at trying to fix it

**Comment by MihaiNueleanu** [comment]
Oh, they have 16 GB free for the first month too, btw. so we can start using it for all logs, find the ansible bug, and then we turn down the log level to `error` only

**Comment by joshuakarjala** [comment]
> Oh, they have 16 GB free for the first month too, btw. so we can start using it for all logs, find the ansible bug, and then we turn down the log level to `error` only

Cool - I guess with the limited number of devices it shouldn't be crazy to begin with.

Maybe take 5min to look at - https://timber.io to see if it's better than Papertrail - seems cool. LMK if you need me to pay somewhere

**Comment by MihaiNueleanu** [comment]
nice. I'll give it a try. I went for papertrail because we used it with heroku. but there are a couple of issues I noticed with it already, so I'm glad to try alternatives :)

**Comment by MihaiNueleanu** [comment]
In their guide, it actually looks easier than with papertrail
https://docs.timber.io/setup/log-forwarders/fluent-bit

And their pricing is better too, isn't it?
https://timber.io/pricing/

**Comment by MihaiNueleanu** [comment]
Managed to get something going with timber. Here's a screenshot:
![image.png](https://images.zenhubusercontent.com/5f241f53c7cdabe34a5ab9e5/6b56a92f-6133-4bfb-b8d1-2cf00d13a3db)

**Comment by MihaiNueleanu** [comment]
I could use some a little idea-sparring around how to handle the logging token in the repository

https://github.com/kihosk/kiosk-os/pull/3

@joshuakarjala

**Comment by joshuakarjala** [comment]
> I could use some a little idea-sparring around how to handle the logging token in the repository
> 
> #3
> 
> @joshuakarjala

what is the problem?

**Comment by MihaiNueleanu** [comment]
Exposing this token might be an issue:
https://github.com/kihosk/kiosk-os/pull/3/files#diff-bd306ba0f165e2035c667334907f9783R19

As you know the kiosk-os repo is currently public, and so I'm thinking it might be an undesirable situation.

**Comment by joshuakarjala** [comment]
> Exposing this token might be an issue:
> https://github.com/kihosk/kiosk-os/pull/3/files#diff-bd306ba0f165e2035c667334907f9783R19
> 
> As you know the kiosk-os repo is currently public, and so I'm thinking it might be an undesirable situation.

Ah like that - well if we upload ansible playbook to s3 and then download - then we don't need to be public repo :D

**Comment by MihaiNueleanu** [comment]
what kinds of authentication does s3 support?

**Comment by MihaiNueleanu** [comment]
Starting to secure the kiosk-os repo: 

Added a github deploy key that only gives access to kiosk-os 

The ansible command should be changed to: 
 ```
sudo ansible-pull --url git@github.com:kihosk/kiosk-os.git update.yml -C origin/test/ansible-update --accept-host-key --private-key /home/pi/.ssh/id_rsa
```

... or similar
